# Generated by Django 5.1.6 on 2025-05-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_userprofile_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
    ]
