"""
Django settings for Authentication project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n#e@j8j5v=^9ajukl6j7h3wag#ppqzdcn43+b84qs*3jvl7cr='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Authentication.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Authentication.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'authentication',
        'USER': 'Farah_20210672@fci.helwan.edu.eg',
        'PASSWORD': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpETmFfNGk0cjdGZ2lnTDNzSElsSTN4Vi1JVSIsImtpZCI6IkpETmFfNGk0cjdGZ2lnTDNzSElsSTN4Vi1JVSJ9.eyJhdWQiOiJodHRwczovL29zc3JkYm1zLWFhZC5kYXRhYmFzZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2FhZGMwZTBhLTY1ZWUtNDcxYS05OWExLTlmODZmYWVjYmFlZC8iLCJpYXQiOjE3NDIxNjc0MzIsIm5iZiI6MTc0MjE2NzQzMiwiZXhwIjoxNzQyMTcyODczLCJhY3IiOiIxIiwiYWlvIjoiQVRRQXkvOFpBQUFBd2RORHo5TTVBWFJ4Z0VXc3QvUU5sTkxJSm9INHp5QUhIQU1xcFgwOG9hZlhhQk9ab0tXOVVSVW45S0R2UGNSSyIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IjIwMjEwNjcyIiwiZ2l2ZW5fbmFtZSI6IkZhcmFoIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTAyLjE5MS4yMTkuOTAiLCJuYW1lIjoiRmFyYWggMjAyMTA2NzIiLCJvaWQiOiI5MzhjZjA0ZC05YTAxLTQ0NGItYmYxYy1lOTJkNTA2MDZmZGQiLCJwdWlkIjoiMTAwMzIwMDFBNkY3NURCOSIsInB3ZF91cmwiOiJodHRwczovL3BvcnRhbC5taWNyb3NvZnRvbmxpbmUuY29tL0NoYW5nZVBhc3N3b3JkLmFzcHgiLCJyaCI6IjEuQVF3QUNnN2NxdTVsR2tlWm9aLUctdXk2N1ZEWVBCTGYyYjFBbE5YSjhIdF9vZ01NQUJnTUFBLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInNpZCI6IjAwMjE5OWE5LWM3ZTgtY2MxYy03NjM1LTA3MjA4ODkxMjVlZiIsInN1YiI6InN3QkJKUXpJVUc0VGZua0ZiZXJWWnlwU19kemQyZ1dmeUIycnR4TXFDQjAiLCJ0aWQiOiJhYWRjMGUwYS02NWVlLTQ3MWEtOTlhMS05Zjg2ZmFlY2JhZWQiLCJ1bmlxdWVfbmFtZSI6IkZhcmFoXzIwMjEwNjcyQGZjaS5oZWx3YW4uZWR1LmVnIiwidXBuIjoiRmFyYWhfMjAyMTA2NzJAZmNpLmhlbHdhbi5lZHUuZWciLCJ1dGkiOiJZZkdLRE5WOEFFU3htSndyV0FhN0FBIiwidmVyIjoiMS4wIiwieG1zX2lkcmVsIjoiMTggMSJ9.eoqz9xNyCdEJw8VD4nNAHPh_xXtBT48PodxBkSSafL0E0_7bqvqUKDblAWB2mAcc3u_u5hZg1PpW6ifDvp6y6Vn2a3rlVovLhc0z9s_0mZEX6SGHZ1ogv8RPpYddTbByuXp5o0xpwY_9fa-lclydooMd04LE2yUNC-AQ1SlOjC0FhU_VP9Yzuqd7h5ENMkrwDssrb7luUZJkQc6bhDySKZANNm8QeHTt_U98sSFDaUUfw18ocOZhVp57-wPepybz7J820UyCG4MK_6xMjkOHlAz_qQGS_FBcsKG6N3v72DGFppX86tC2fUsYl7Qc-dDjAVBw8hyvJbZ9bD_C0Kka4w',
        'HOST': 'senior-demo.postgres.database.azure.com',  # or your database server IP
        'PORT': '5432',       # Default PostgreSQL port
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'base.backends.EmailOrUsernameBackend',  
    'django.contrib.auth.backends.ModelBackend',  
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Redirect URLs after login/logout
#LOGIN_REDIRECT_URL = '/'
#LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = 'base:home'
LOGOUT_REDIRECT_URL = 'base:login'
