"""
Django settings for Authentication project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR is:", BASE_DIR)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n#e@j8j5v=^9ajukl6j7h3wag#ppqzdcn43+b84qs*3jvl7cr='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Authentication.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR / "templates"],
        # 'DIRS': [os.path.join(BASE_DIR, "templates")],
        'DIRS': [BASE_DIR / 'base' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Authentication.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
# }

import dj_database_url
import os

# Replace [YOUR-PASSWORD] with your actual database password
DATABASE_URL = "postgresql://postgres:k2L6a6ey%236RyZw4@jeodmvxxqnruvkvdzhlm.supabase.co:5432/postgres"

# DATABASES = {
#     'default': dj_database_url.parse(DATABASE_URL)
# }

import dj_database_url

DATABASES = {
    'default': dj_database_url.parse("postgresql://postgres:k2L6a6ey%236RyZw4@jeodmvxxqnruvkvdzhlm.supabase.co:5432/postgres", conn_max_age=600, ssl_require=True)
}



# DATABASES = {
#      'default': {
#          'ENGINE': 'django.db.backends.postgresql',
#          'NAME': 'postgres',  # Supabase default
#          'USER': 'postgres',  # Supabase default
#          'PASSWORD': 'k2L6a6ey#6RyZw4',  # Go to Settings → Database → Reset password if needed
#          'HOST': 'jeodmvxxqnruvkvdzhlm.supabase.co',
#          'PORT': '5432',
#          'OPTIONS': {
#              'sslmode': 'require',  # Important for Supabase connections
#              'sslrootcert': r'C:\Users\Dell\Desktop\supabase\prod-ca-2021.crt',
#          },
#      }
#  }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.jeodmvxxqnruvkvdzhlm',  # Pooler username
        'PASSWORD': 'k2L6a6ey#6RyZw4',  # Replace with your actual password
        'HOST': 'aws-0-eu-north-1.pooler.supabase.com',  # Pooler host
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}

# At the top of settings.py (with other imports)
# import os
# import dj_database_url
# from urllib.parse import quote_plus
# from pathlib import Path

# # Build paths inside the project
# BASE_DIR = Path(__file__).resolve().parent.parent

# # ... other settings like SECRET_KEY, DEBUG, etc. ...

# # Database configuration (replace your existing DATABASES section)
# DB_PASSWORD = "k2L6a6ey#6RyZw4"  # ← PUT YOUR REAL PASSWORD HERE
# DB_USER = "postgres"
# DB_HOST = "jeodmvxxqnruvkvdzhlm.supabase.co"
# DB_NAME = "postgres"

# encoded_password = quote_plus(DB_PASSWORD)
# DATABASE_URL = f"postgresql://{DB_USER}:{encoded_password}@{DB_HOST}:5432/{DB_NAME}"

# DATABASES = {
#     'default': dj_database_url.parse(DATABASE_URL)
# }


# from supabase import create_client, Client

# # Replace with your actual values from Supabase Dashboard
# url = "https://jeodmvxxqnruvkvdzhlm.supabase.co"
# key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implb2Rtdnh4cW5ydXZrdmR6aGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Nzc5MTIsImV4cCI6MjA2NTE1MzkxMn0.x4WtUmlsnC5wYT_SaK7DHXBbTZWrU_AaEA7Nk4KWldQ"  # Get from Dashboard -> Settings -> API

# try:
#     supabase: Client = create_client(url, key)
    
#     # Simple test - this should work over HTTPS
#     print("Testing Supabase connection...")
    
#     # Try to access a system table or create a test
#     response = supabase.rpc('version').execute()
#     print("✅ Supabase REST API works!")
#     print(f"Response: {response}")
    
# except Exception as e:
#     print(f"❌ Error connecting to Supabase: {e}")



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'base.backends.EmailOrUsernameBackend',  
    'django.contrib.auth.backends.ModelBackend',  
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

from pathlib import Path



STATIC_URL = 'static/'

# STATICFILES_DIRS = [BASE_DIR / "static"]


STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Redirect URLs after login/logout
#LOGIN_REDIRECT_URL = '/'
#LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = 'base:home'
LOGOUT_REDIRECT_URL = 'base:login'


mail =os.environ.get("MAIL")
mail_pass =os.environ.get("MAIL_PASSWORD")

EMAIL_BACKEND ="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST ="smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER =mail
EMAIL_HOST_PASSWORD =mail_pass
DEFAULT_FROM_EMAIL =mail
EMAIL_SUBJECT_PREFIX ="Password Recovery"