version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: backend-fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
    volumes:
      - .:/apps
    env_file:
      - .env

  backend-worker:
    build: .
    container_name: backend-worker
    depends_on:
      - redis
      - fastapi-app
    environment:
      - PYTHONPATH=/apps
    command: [ "celery", "-A", "apps.leaderboard.worker", "worker", "--loglevel=info" ]

    volumes:
      - .:/apps
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

volumes:
  postgres_data:
