version: '3.8'

services:
  app:
    build:
      context: .
    container_name: contenthandler-app
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: contenthandler-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: farrahpost
      POSTGRES_DB: contenthandlerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: contenthandler-redis
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
      - --rename-command FLUSHDB ""
      - --rename-command FLUSHALL ""
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: