# Generated by Django 5.1.6 on 2025-03-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile_full_name_userprofile_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
